name: Upload Dist To Tencent COS

on:
    push:
        branches: gh-page
    pull_request:
        branches: gh-page
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        
      - name: Install coscmd
        run: sudo pip install coscmd
        
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SecretId }}
          SECRET_KEY: ${{ secrets.SecretKey }}
          BUCKET: hzsb-site-1301539318
          REGION: ap-hongkong
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        
      - name: Upload
        run: coscmd upload -rs --delete -f ./ /
